### PR TITLE
Fix linux build of artview 1.2

### LINKED ISSUE #1: Missing lib
@jjhelmus Linux is failing with:

```
ImportError: libXext.so.6: cannot open shared object file: No such file or directory
```

### PR DESCRIPTION
**Pull request by jjhelmus**
closes #1
[skip appveyor]

### CODE REVIEW

**Comment by ocefpaf** [comment]
@jjhelmus Did you get automatically added to this repo?

**Comment by jjhelmus** [comment]
Does not look like it, I don't have write access.

**Comment by ocefpaf** [comment]
In https://github.com/conda-forge/wradlib-feedstock/pull/1#issuecomment-192600630 @pelson mention that restarting conda-forge/conda-forge.github.io would fix this, but Travis-CI is failing there (see https://travis-ci.org/conda-forge/conda-forge.github.io/jobs/114014860).  I am adding you manually for now.

**Comment by pelson** [comment]
Thanks @jjhelmus. If you have the power, merge merge merge!
We'll be working through an approach to solve these problems in the longer term soon.

**Pull request merged**
